### ISSUE TITLE
Class 'OTPHP\TOTP' not found

### ISSUE THREAD

**Issue by xperseguers** [pgampe/authenticator#10]
After installing, configuring my BE user account and logging out (clearing cache as well), the BE form totally crashes (white page, 500 error) with:

```
PHP Fatal error:  Class 'OTPHP\TOTP' not found in /path/to/typo3_src-7.6.4/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 4511
```

**Comment by pgampe** [comment]
I can confirm this on 7-6-dev

**Comment by pgampe** [comment]
This is a problem of the TYPO3 composer mode. If you use the ``composer mode``, then you need to add the autoload information to the ``composer.json`` file.
The class ``OTPHP\TOTP`` is in ``typo3conf/ext/authenticator/Resources/Private/Php/otphp/lib/otphp.php``.

It is not possible to support both 6.2 and 7.6 at the same time because of the composer issues (adding a ``composer.json`` will crash in 6.2).

**Comment by pgampe** [comment]
I should properly just drop the lib and implement the functionality on my own.

**Comment by Cretection** [comment]
How might look like a composer.json? I tested it but it does not work for me :(

**Comment by jensmarquardt** [comment]
This is working for me:

```
"psr-4": {
	...
	"Tx\\Authenticator\\": "web/typo3conf/ext/authenticator/Classes/"
},
"classmap": [
    "web/typo3conf/ext/authenticator/Resources/Private/Php/otphp/"
]
```
